/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import TheCheckOut.CheckOut;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 * Created Mar 19, 2019
 * @author Roberto Gomez
 * @version 2
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_LibrarySystem = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_checkOut = new javax.swing.JButton();
        btn_checkIn = new javax.swing.JButton();
        btn_addUsers = new javax.swing.JButton();
        btn_addBooks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homeDesktop = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_LibrarySystem.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        lbl_LibrarySystem.setText("Library System");
        jPanel1.add(lbl_LibrarySystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lbl_date.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_date.setText("Date");
        jPanel1.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 170, -1));

        lbl_time.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_time.setText("Time");
        jPanel1.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 170, -1));

        jToolBar1.setRollover(true);
        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        btn_checkOut.setText("Check Out");
        btn_checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btn_checkIn.setText("Check In");
        btn_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkInActionPerformed(evt);
            }
        });
        jPanel1.add(btn_checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btn_addUsers.setText("Add Users");
        btn_addUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        btn_addBooks.setText("Add Books");
        btn_addBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addBooksActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 620));

        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 570));

        javax.swing.GroupLayout homeDesktopLayout = new javax.swing.GroupLayout(homeDesktop);
        homeDesktop.setLayout(homeDesktopLayout);
        homeDesktopLayout.setHorizontalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        homeDesktopLayout.setVerticalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(homeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 1010, 570));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clock()
    {
        Thread clock=new Thread()
        {
            public void run()
            {
                try {
                    while(true)
                    {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH)+1;
                        int year = cal.get(Calendar.YEAR);
                        
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        
                        lbl_time.setText ( hour + ":" + minute + ":" + second);
                        lbl_date.setText (month + "-" + day + "-" + year);
                        
                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        };
        clock.start();
    }
    
    
    
    
    
    
    
    private void btn_addUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUsersActionPerformed
        homeDesktop.removeAll();
        TheMembers.AddMember am = new TheMembers.AddMember();
        homeDesktop.add(am).setVisible(true);
        
    }//GEN-LAST:event_btn_addUsersActionPerformed

    private void btn_addBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addBooksActionPerformed
        homeDesktop.removeAll();
        TheBooks.AddBooks ab = new TheBooks.AddBooks();
        homeDesktop.add(ab).setVisible(true);
        
    }//GEN-LAST:event_btn_addBooksActionPerformed

    private void btn_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkOutActionPerformed
        homeDesktop.removeAll();
        TheCheckOut.CheckOut co = new TheCheckOut.CheckOut();
        homeDesktop.add(co).setVisible(true);
        
    }//GEN-LAST:event_btn_checkOutActionPerformed

    private void btn_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkInActionPerformed
        homeDesktop.removeAll();
        CheckIn ci = new CheckIn();
        homeDesktop.add(ci).setVisible(true);
        
    }//GEN-LAST:event_btn_checkInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addBooks;
    private javax.swing.JButton btn_addUsers;
    private javax.swing.JButton btn_checkIn;
    private javax.swing.JButton btn_checkOut;
    private javax.swing.JDesktopPane homeDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_LibrarySystem;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    // End of variables declaration//GEN-END:variables
}
