/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import TheCheckIn.CheckIn;
import TheCheckOut.CheckOut;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 * Created Mar 19, 2019
 * @author Roberto Gomez
 * @version 2
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_LibrarySystem = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_inventory = new javax.swing.JButton();
        btn_allusers = new javax.swing.JButton();
        btn_tool1 = new javax.swing.JButton();
        btn_tool2 = new javax.swing.JButton();
        btn_developers = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_checkOut = new javax.swing.JButton();
        btn_checkIn = new javax.swing.JButton();
        btn_addUsers = new javax.swing.JButton();
        btn_addBooks = new javax.swing.JButton();
        btn_addStaff = new javax.swing.JButton();
        lblUHDbackground = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homeDesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_time.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_time.setText("Time");
        jPanel1.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 150, -1));

        lbl_date.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_date.setText("Date");
        jPanel1.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 140, -1));

        lbl_LibrarySystem.setBackground(java.awt.Color.red);
        lbl_LibrarySystem.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        lbl_LibrarySystem.setForeground(java.awt.Color.blue);
        lbl_LibrarySystem.setText("UNIVERSITY OF HOUSTON - DOWNTOWN          Library");
        jPanel1.add(lbl_LibrarySystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbl_title.setBackground(java.awt.Color.red);
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1190, 50));

        jToolBar1.setRollover(true);

        btn_inventory.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_inventory.setForeground(java.awt.Color.blue);
        btn_inventory.setText("Inventory");
        btn_inventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_inventory.setFocusable(false);
        btn_inventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inventory.setMaximumSize(new java.awt.Dimension(140, 27));
        btn_inventory.setPreferredSize(new java.awt.Dimension(140, 27));
        btn_inventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventoryActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_inventory);

        btn_allusers.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_allusers.setForeground(java.awt.Color.blue);
        btn_allusers.setText("All Users");
        btn_allusers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_allusers.setFocusable(false);
        btn_allusers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_allusers.setMaximumSize(new java.awt.Dimension(140, 29));
        btn_allusers.setPreferredSize(new java.awt.Dimension(140, 29));
        btn_allusers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_allusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allusersActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_allusers);

        btn_tool1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_tool1.setForeground(java.awt.Color.blue);
        btn_tool1.setText("Tool 1");
        btn_tool1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tool1.setFocusable(false);
        btn_tool1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tool1.setMaximumSize(new java.awt.Dimension(140, 29));
        btn_tool1.setPreferredSize(new java.awt.Dimension(140, 29));
        btn_tool1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_tool1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tool1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_tool1);

        btn_tool2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_tool2.setForeground(java.awt.Color.blue);
        btn_tool2.setText("Tool 2");
        btn_tool2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tool2.setFocusable(false);
        btn_tool2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tool2.setMaximumSize(new java.awt.Dimension(140, 29));
        btn_tool2.setPreferredSize(new java.awt.Dimension(140, 29));
        btn_tool2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_tool2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tool2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_tool2);

        btn_developers.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_developers.setForeground(java.awt.Color.blue);
        btn_developers.setText("Developers");
        btn_developers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_developers.setFocusable(false);
        btn_developers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_developers.setMaximumSize(new java.awt.Dimension(140, 29));
        btn_developers.setPreferredSize(new java.awt.Dimension(140, 29));
        btn_developers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_developers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_developersActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_developers);

        btn_exit.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btn_exit.setForeground(java.awt.Color.blue);
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setFocusable(false);
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setMaximumSize(new java.awt.Dimension(140, 29));
        btn_exit.setPreferredSize(new java.awt.Dimension(140, 29));
        btn_exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_exit);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        btn_checkOut.setText("Check Out");
        btn_checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btn_checkIn.setText("Check In");
        btn_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkInActionPerformed(evt);
            }
        });
        jPanel1.add(btn_checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btn_addUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/Users.jpg"))); // NOI18N
        btn_addUsers.setText("Add User");
        btn_addUsers.setMaximumSize(new java.awt.Dimension(148, 73));
        btn_addUsers.setMinimumSize(new java.awt.Dimension(148, 73));
        btn_addUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 250, 160, -1));

        btn_addBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/books.jpg"))); // NOI18N
        btn_addBooks.setText("Add Book");
        btn_addBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addBooksActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 340, 160, 60));

        btn_addStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/Staff.jpg"))); // NOI18N
        btn_addStaff.setText("Add Staff");
        btn_addStaff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addStaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        lblUHDbackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUHDbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/uh_downtown.jpg"))); // NOI18N
        lblUHDbackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblUHDbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 620));

        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 570));

        javax.swing.GroupLayout homeDesktopLayout = new javax.swing.GroupLayout(homeDesktop);
        homeDesktop.setLayout(homeDesktopLayout);
        homeDesktopLayout.setHorizontalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        homeDesktopLayout.setVerticalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(homeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 1010, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clock()
    {
        Thread clock=new Thread()
        {
            public void run()
            {
                try {
                    while(true)
                    {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH)+1;
                        int year = cal.get(Calendar.YEAR);
                        
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        
                        lbl_time.setText ( hour + ":" + minute + ":" + second);
                        lbl_date.setText (month + "-" + day + "-" + year);
                        
                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        };
        clock.start();
    }
    
    
    
    
    
    
    
    private void btn_addUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUsersActionPerformed
        homeDesktop.removeAll();
        TheMembers.AddMember am = new TheMembers.AddMember();
        homeDesktop.add(am).setVisible(true);
        
    }//GEN-LAST:event_btn_addUsersActionPerformed

    private void btn_addBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addBooksActionPerformed
        homeDesktop.removeAll();
        TheBooks.AddBooks ab = new TheBooks.AddBooks();
        homeDesktop.add(ab).setVisible(true);
        
    }//GEN-LAST:event_btn_addBooksActionPerformed

    private void btn_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkOutActionPerformed
        homeDesktop.removeAll();
        TheCheckOut.CheckOut co = new TheCheckOut.CheckOut();
        homeDesktop.add(co).setVisible(true);
        
    }//GEN-LAST:event_btn_checkOutActionPerformed

    private void btn_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkInActionPerformed
        homeDesktop.removeAll();
        TheCheckIn.CheckIn ci = new TheCheckIn.CheckIn();
        homeDesktop.add(ci).setVisible(true);
        
    }//GEN-LAST:event_btn_checkInActionPerformed

    private void btn_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventoryActionPerformed
        homeDesktop.removeAll();
        TheBooks.Inventory inv = new TheBooks.Inventory();
        homeDesktop.add(inv).setVisible(true);
    }//GEN-LAST:event_btn_inventoryActionPerformed

    private void btn_allusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allusersActionPerformed
        homeDesktop.removeAll();
        TheMembers.AllUsers au = new TheMembers.AllUsers();
        homeDesktop.add(au).setVisible(true);
    }//GEN-LAST:event_btn_allusersActionPerformed

    private void btn_tool1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tool1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tool1ActionPerformed

    private void btn_tool2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tool2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tool2ActionPerformed

    private void btn_developersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_developersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_developersActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addStaffActionPerformed
        homeDesktop.removeAll();
        TheStaff.AddStaff am = new TheStaff.AddStaff();
        homeDesktop.add(am).setVisible(true);
    }//GEN-LAST:event_btn_addStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addBooks;
    private javax.swing.JButton btn_addStaff;
    private javax.swing.JButton btn_addUsers;
    private javax.swing.JButton btn_allusers;
    private javax.swing.JButton btn_checkIn;
    private javax.swing.JButton btn_checkOut;
    private javax.swing.JButton btn_developers;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_inventory;
    private javax.swing.JButton btn_tool1;
    private javax.swing.JButton btn_tool2;
    private javax.swing.JDesktopPane homeDesktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUHDbackground;
    private javax.swing.JLabel lbl_LibrarySystem;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration//GEN-END:variables
}
