/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TheTeam;

/**
 *
 * @author Rob77
 */
public class Developers extends javax.swing.JInternalFrame {

    /**
     * Creates new form Developers
     */
    public Developers() {
        initComponents();

    }


    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_lifecyclemodel = new javax.swing.JLabel();
        lbl_rapidprototyping = new javax.swing.JLabel();
        lbl_teamorganization = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("Project  Library v 2.0");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel2.setBackground(java.awt.Color.black);
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.green);
        jLabel2.setText("Developer Team :");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.green);
        jLabel3.setText("Roberto Gomez ");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel4.setBackground(java.awt.Color.black);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.green);
        jLabel4.setText("Nina Lalonde");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel5.setBackground(java.awt.Color.black);
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.green);
        jLabel5.setText("Alan Saavedra");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        lbl_lifecyclemodel.setBackground(java.awt.Color.black);
        lbl_lifecyclemodel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_lifecyclemodel.setForeground(java.awt.Color.green);
        lbl_lifecyclemodel.setText("Life Cycle Model :");
        lbl_lifecyclemodel.setOpaque(true);
        jPanel1.add(lbl_lifecyclemodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        lbl_rapidprototyping.setBackground(java.awt.Color.black);
        lbl_rapidprototyping.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_rapidprototyping.setForeground(java.awt.Color.green);
        lbl_rapidprototyping.setText("Rapid Prototyping");
        lbl_rapidprototyping.setOpaque(true);
        jPanel1.add(lbl_rapidprototyping, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        lbl_teamorganization.setBackground(java.awt.Color.black);
        lbl_teamorganization.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_teamorganization.setForeground(java.awt.Color.green);
        lbl_teamorganization.setText("Team Organization :");
        lbl_teamorganization.setOpaque(true);
        jPanel1.add(lbl_teamorganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel9.setBackground(java.awt.Color.black);
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.green);
        jLabel9.setText("Chief Programmer");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/UHD Team.jpg"))); // NOI18N
        jPanel1.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_lifecyclemodel;
    private javax.swing.JLabel lbl_rapidprototyping;
    private javax.swing.JLabel lbl_teamorganization;
    // End of variables declaration//GEN-END:variables
}
