/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TheCheckOut;

/**
 *
 * @author Rob77
 */
public class CheckOut extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_books = new javax.swing.JPanel();
        txt_bookid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_booktitle = new javax.swing.JTextField();
        txt_booktype = new javax.swing.JTextField();
        panel_members = new javax.swing.JPanel();
        lbl_account = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        txt_account = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_controls = new javax.swing.JPanel();
        btn_clear = new javax.swing.JButton();
        btn_checkout = new javax.swing.JButton();
        panel_dates = new javax.swing.JPanel();
        lbl_issuedate = new javax.swing.JLabel();
        txt_issuedate = new javax.swing.JTextField();
        lbl_returndate = new javax.swing.JLabel();
        txt_returndate = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_books.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("Book ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Book Title");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Book Type");

        javax.swing.GroupLayout panel_booksLayout = new javax.swing.GroupLayout(panel_books);
        panel_books.setLayout(panel_booksLayout);
        panel_booksLayout.setHorizontalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_booksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_booksLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_booktype, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(246, Short.MAX_VALUE))
                    .addGroup(panel_booksLayout.createSequentialGroup()
                        .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_booksLayout.createSequentialGroup()
                                .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_booktitle)))))
        );
        panel_booksLayout.setVerticalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_booksLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_booktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_booktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(panel_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 480, -1));

        panel_members.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_account.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_account.setText("Account");

        lbl_firstname.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_firstname.setText("First Name");

        lbl_lastname.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_lastname.setText("Last Name");

        lbl_status.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_status.setText("Status");

        javax.swing.GroupLayout panel_membersLayout = new javax.swing.GroupLayout(panel_members);
        panel_members.setLayout(panel_membersLayout);
        panel_membersLayout.setHorizontalGroup(
            panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_membersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_account)
                    .addComponent(lbl_firstname)
                    .addComponent(lbl_lastname)
                    .addComponent(lbl_status))
                .addGap(74, 74, 74)
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_account, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(txt_status))
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastname))
                .addGap(26, 26, 26))
        );
        panel_membersLayout.setVerticalGroup(
            panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_membersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_account)
                    .addComponent(txt_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_firstname)
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastname)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel_membersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(panel_members, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 980, 170));

        panel_controls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_clear.setText("CLEAR");

        btn_checkout.setText("CHECK OUT");

        javax.swing.GroupLayout panel_controlsLayout = new javax.swing.GroupLayout(panel_controls);
        panel_controls.setLayout(panel_controlsLayout);
        panel_controlsLayout.setHorizontalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_controlsLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(btn_checkout)
                .addGap(33, 33, 33))
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_controlsLayout.setVerticalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btn_clear)
                .addGap(26, 26, 26)
                .addComponent(btn_checkout)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel1.add(panel_controls, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 160, 300));

        panel_dates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_issuedate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_issuedate.setText("Issue Date");

        lbl_returndate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_returndate.setText("Return Date");

        javax.swing.GroupLayout panel_datesLayout = new javax.swing.GroupLayout(panel_dates);
        panel_dates.setLayout(panel_datesLayout);
        panel_datesLayout.setHorizontalGroup(
            panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_issuedate)
                .addGap(61, 61, 61)
                .addComponent(txt_issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(lbl_returndate)
                .addGap(55, 55, 55)
                .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        panel_datesLayout.setVerticalGroup(
            panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_issuedate)
                    .addComponent(txt_issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_returndate)
                    .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(panel_dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 810, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_issuedate;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_returndate;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPanel panel_books;
    private javax.swing.JPanel panel_controls;
    private javax.swing.JPanel panel_dates;
    private javax.swing.JPanel panel_members;
    private javax.swing.JTextField txt_account;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_booktitle;
    private javax.swing.JTextField txt_booktype;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_issuedate;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_returndate;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
