/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TheCheckOut;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rob77
 */
public class CheckOut extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_controls = new javax.swing.JPanel();
        btn_clear = new javax.swing.JButton();
        btn_checkout = new javax.swing.JButton();
        txt_transaction = new javax.swing.JLabel();
        lbl_transactionid = new javax.swing.JLabel();
        panel_books = new javax.swing.JPanel();
        txt_bookid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_booktitle = new javax.swing.JTextField();
        txt_booktype = new javax.swing.JTextField();
        panel_dates = new javax.swing.JPanel();
        lbl_issuedate = new javax.swing.JLabel();
        txt_issuedate = new javax.swing.JTextField();
        lbl_returndate = new javax.swing.JLabel();
        txt_returndate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbl_account = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        txt_account = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("Check Out");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(828, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        panel_controls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_clear.setText("CLEAR");

        btn_checkout.setText("CHECK OUT");

        txt_transaction.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        txt_transaction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lbl_transactionid.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_transactionid.setText("Transacction ID");

        javax.swing.GroupLayout panel_controlsLayout = new javax.swing.GroupLayout(panel_controls);
        panel_controls.setLayout(panel_controlsLayout);
        panel_controlsLayout.setHorizontalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_transactionid)
                    .addComponent(txt_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_checkout)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panel_controlsLayout.setVerticalGroup(
            panel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_transactionid)
                .addGap(25, 25, 25)
                .addComponent(txt_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_clear)
                .addGap(42, 42, 42)
                .addComponent(btn_checkout)
                .addGap(65, 65, 65))
        );

        jPanel1.add(panel_controls, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 160, 300));

        panel_books.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt_bookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bookidKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("Book ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Book Title");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Book Type");

        javax.swing.GroupLayout panel_booksLayout = new javax.swing.GroupLayout(panel_books);
        panel_books.setLayout(panel_booksLayout);
        panel_booksLayout.setHorizontalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_booksLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_booksLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_booktype, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(246, Short.MAX_VALUE))
                    .addGroup(panel_booksLayout.createSequentialGroup()
                        .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_booksLayout.createSequentialGroup()
                                .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_booktitle)))))
        );
        panel_booksLayout.setVerticalGroup(
            panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_booksLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_booktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_booktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(panel_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 220));

        panel_dates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_issuedate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_issuedate.setText("Issue Date");

        lbl_returndate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_returndate.setText("Return Date");

        javax.swing.GroupLayout panel_datesLayout = new javax.swing.GroupLayout(panel_dates);
        panel_dates.setLayout(panel_datesLayout);
        panel_datesLayout.setHorizontalGroup(
            panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_issuedate)
                .addGap(61, 61, 61)
                .addComponent(txt_issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(lbl_returndate)
                .addGap(55, 55, 55)
                .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        panel_datesLayout.setVerticalGroup(
            panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_issuedate)
                    .addComponent(txt_issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_returndate)
                    .addComponent(txt_returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(panel_dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 810, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 980, 140));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_account.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_account.setText("Account");

        lbl_firstname.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_firstname.setText("First Name");

        lbl_lastname.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_lastname.setText("Last Name");

        lbl_status.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lbl_status.setText("Status");

        txt_account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_accountKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_account)
                    .addComponent(lbl_firstname)
                    .addComponent(lbl_lastname)
                    .addComponent(lbl_status))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_account)
                    .addComponent(txt_firstname)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txt_status))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_account)
                    .addComponent(txt_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_firstname)
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lastname)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_status))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 330, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
       // Feb 19, 2019 Roberto: This section search for a Record in the file by Employee ID
        public void searchAccount (String searchterm, String filepath) throws FileNotFoundException
        {
            int count = 0;
            Scanner x;
            boolean found = false;
            String account = "";
            String firstName = "";
            String lastName = "";
            String birthday;
            String gender;
            String email;
            String phone;
            String status = null;
            
            try
            {
                x = new Scanner(new File(filepath));
                x.useDelimiter("[,\n]");
                
                while(x.hasNext() && !found )
                {
                    account = x.next();
                    firstName = x.next();
                    lastName = x.next();
                    birthday = x.next();                
                    gender = x.next();
                    email = x.next();
                    phone = x.next();
                    status = x.next();
                    
                    if ( account.equals(searchterm))
                    {
                        found = true;                      
                    }
                }
                if (found)
                {
                    txt_firstname.setText(firstName);
                    txt_lastname.setText(lastName);
                    txt_status.setText(status);
                }
                else
                {
                    count = count + 1;
                    if (count > 4)
                    {
                    JOptionPane.showMessageDialog(null,"ACCOUNT NOT found");
                    }
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error");
            }   
        }
    
       // Feb 19, 2019 Roberto: This section search for a book in the file by Book ID
        public void searchBooks (String searchterm, String filepath) throws FileNotFoundException
        {
            int count = 0;
            Scanner x;
            boolean found = false;
            String bookid = "";
            String booktitle = "";
            String barcode = "";
            String bookdate;
            String category;
            String booktype = null;
            String publisher;
            String bookprice;
            
            try
            {
                x = new Scanner(new File(filepath));
                x.useDelimiter("[,\n]");
                
                while(x.hasNext() && !found )
                {
                    bookid = x.next();
                    booktitle = x.next();
                    barcode = x.next();
                    bookdate = x.next();                
                    category = x.next();
                    booktype = x.next();
                    publisher = x.next();
                    bookprice = x.next();
                    
                    if ( bookid.equals(searchterm))
                    {
                        found = true;
                    }
                }
                if (found)
                {
                    txt_booktitle.setText(booktitle);
                    txt_booktype.setText(booktype);     
                }
                else
                {
                    count = count + 1;
                    if (count > 6)
                    {
                        JOptionPane.showMessageDialog(null,"BOOK NOT found");
                    }
                }                
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error ON EXCEPTION" + e);
            }   
        }
    
    
    
    
    private void txt_accountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_accountKeyReleased
        // Feb 19, 2019 Roberto: This section will search by Account
        String searchterm = txt_account.getText();

        try {
            searchAccount(searchterm, "member.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "SEARCH Account ERROR");
        }
    }//GEN-LAST:event_txt_accountKeyReleased

    private void txt_bookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bookidKeyReleased
        // Feb 19, 2019 Roberto: This section will search by Book ID
        String searchterm = txt_bookid.getText();

        try {
            searchBooks(searchterm, "book.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "SEARCH Book ERROR");
        }
    }//GEN-LAST:event_txt_bookidKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_issuedate;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_returndate;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_transactionid;
    private javax.swing.JPanel panel_books;
    private javax.swing.JPanel panel_controls;
    private javax.swing.JPanel panel_dates;
    private javax.swing.JTextField txt_account;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_booktitle;
    private javax.swing.JTextField txt_booktype;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_issuedate;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_returndate;
    private javax.swing.JTextField txt_status;
    private javax.swing.JLabel txt_transaction;
    // End of variables declaration//GEN-END:variables
}
